
version: 2.1
defaults: &static
  docker:
  - image: circleci/node:13.8.0
jobs:
  build:
    <<: *static
    steps:
      - checkout
      - run: npm i
      - run: npm run lint
  test:
    <<: *static
    steps:
      - checkout
      - run: npm i
      - run: npm run test
  analyze:
    <<: *static
    steps:
      - checkout
      - run: npm i
      - run: npm audit
workflows:
  CI-Pipeline-workflow:
    jobs:
      - build
      - test:
          requires: build
      - analyze:
          requires: test
